### ISSUE TITLE
test error

### ISSUE THREAD

**Issue by Brli** [chewing/libchewing#148]
Making check in test
make[1]: Entering directory `/tmp/libchewing/src/libchewing-0.4.0/test'
make  performance testchewing simulate randkeystroke genkeystroke test-bopomofo test-config test-easy-symbol test-error-handling test-fullshape test-key2pho test-keyboard test-keyboardless test-logger test-mmap test-path test-reset test-regression test-symbol test-special-symbol test-struct-size test-userphrase test-utf8  testhelper.h 
make[2]: Entering directory `/tmp/libchewing/src/libchewing-0.4.0/test'
make[2]: `performance' is up to date.
  CCLD   testchewing
../test/.libs/libtesthelper.a(testhelper.o): In function `internal_ok_buffer':
testhelper.c:(.text+0x6ac): undefined reference to `ueStrLen'
../test/.libs/libtesthelper.a(testhelper.o): In function `internal_ok_candidate_len':
testhelper.c:(.text+0xb54): undefined reference to `ueStrLen'
../test/.libs/libtesthelper.a(testhelper.o): In function `internal_has_userphrase':
testhelper.c:(.text+0xd16): undefined reference to `UintFromPhone'
testhelper.c:(.text+0xd5c): undefined reference to `UserGetPhraseFirst'
testhelper.c:(.text+0xd80): undefined reference to `UserGetPhraseNext'
testhelper.c:(.text+0xdaa): undefined reference to `UserGetPhraseEnd'
collect2: error: ld returned 1 exit status
make[2]: *** [testchewing] Error 1
make[2]: Leaving directory `/tmp/libchewing/src/libchewing-0.4.0/test'
make[1]: *** [check-am] Error 2
make[1]: Leaving directory `/tmp/libchewing/src/libchewing-0.4.0/test'
make: *** [check-recursive] Error 1

**Comment by jserv** [comment]
I believe it is invalid for GIT version.

**Comment by Sharmajee9** [comment]
Even I observed same failures.

If I configure with --disable-static option make check will fail.

./configure --disable-static 

make check
../test/.libs/libtesthelper.a(testhelper.o): In function `internal_ok_buffer':
/usr/share/mcpsource/libchewing-0.3.4-6.el7_1.ibm.1-source/test/testhelper.c:260: undefined reference to `ueStrLen'
../test/.libs/libtesthelper.a(testhelper.o): In function `internal_has_userphrase':
/usr/share/mcpsource/libchewing-0.3.4-6.el7_1.ibm.1-source/test/testhelper.c:386: undefined reference to `UintFromPhone'
/usr/share/mcpsource/libchewing-0.3.4-6.el7_1.ibm.1-source/test/testhelper.c:389: undefined reference to `HashFindPhonePhrase'
collect2: error: ld returned 1 exit status
make[2]: *** [testchewing] Error 1


But if I run with out --disable-static option every thing works fine.

Seems like test required static binaries to be enabled.
Any suggestions ?

**Comment by jserv** [comment]
@Sharmajee9 : It seems that you were using old version (0.3.4) of libchewing, right? Why don't you use the latest stable release?

**Comment by Sharmajee9** [comment]
@jserv : Thanks for your prompt response , let me give a try with the latest release. :+1:

**Comment by Sharmajee9** [comment]
@jserv : Hi Jim I tried with latest git repo, still with --disable-static options make check is failing.

Fail logs : 

make[2]: Entering directory `/root/libchewing-master/test'
  CC       performance.o
  CCLD     performance
  CC       testchewing.o
  CCLD     testchewing
../test/.libs/libtesthelper.a(testhelper.o): In function `internal_ok_buffer':
/root/libchewing-master/test/testhelper.c:302: undefined reference to `ueStrLen'
../test/.libs/libtesthelper.a(testhelper.o): In function `internal_ok_candidate_len':
/root/libchewing-master/test/testhelper.c:393: undefined reference to `ueStrLen'
../test/.libs/libtesthelper.a(testhelper.o): In function `internal_has_userphrase':
/root/libchewing-master/test/testhelper.c:448: undefined reference to `UintFromPhone'
/root/libchewing-master/test/testhelper.c:451: undefined reference to `UserGetPhraseFirst'
/root/libchewing-master/test/testhelper.c:452: undefined reference to `UserGetPhraseNext'
/root/libchewing-master/test/testhelper.c:461: undefined reference to `UserGetPhraseEnd'
collect2: error: ld returned 1 exit status
make[2]: *** [testchewing] Error 1



But after using simple ./configure make check passes.

make check

============================================================================
Testsuite summary for libchewing 0.4.0
============================================================================
# TOTAL: 18
# PASS:  18
# SKIP:  0
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
============================================================================

Any suggestions ..??
