### ISSUE TITLE
Fix j, k selection when symbol in between

### ISSUE THREAD

**Issue by czchen** [chewing/libchewing#149]
See `test_jk_selection`. It looks like j, k selection is broken if there is a symbol in between.

**Comment by jserv** [comment]
Is it still valid for latest libchewing + ibus?

**Comment by czchen** [comment]
@jserv The case `test_jk_selection` still fails in git HEAD

**Comment by redfish-lee** [comment]
I've got the same issue for latest fcitx + libchewing

**Comment by czchen** [comment]
Fixed in #221
