### ISSUE TITLE
候選清單未正確地開啟

### ISSUE THREAD

**Issue by hiunnhue** [chewing/libchewing#160]
Env:

* ibus-chewing: 1.4.10.1-1
* libchewing3: 0.4.0+201408140531+1185~ubuntu14.04.1 (from PPA)

Steps:

1. 輸入 「，實際；測試。」
2. 移動游標向前，以 Backspace 刪除「，」
3. 剩下的兩個標點符號「；」和「。」都無法開啟候選清單

**Comment by czchen** [comment]
Fixed in #181
