### ISSUE TITLE
Add APIs to convert between phone and bopomofo

### ISSUE THREAD

**Issue by czchen** [chewing/libchewing#166]
Phone is exported via `chewing_get_phoneSeq()`. However, the phone is meaningless if libchewing does not provide an API to convert it to bopomofo. We shall provide an API to convert phone to bopomofo.

**Comment by school510587** [comment]
Some member got confused about the meaning of "phone" in chewing_get_phoneSeq and key2pho.c [0]
Phone in chewing_get_phoneSeq represents Uint in key2pho.c, but phone in key2pho.c stands for the UTF8-encoded Bopomofo string.
Should we solve this inconsistency?
EG. Rename some functions in key2pho.c. The name Uint seems not obviously related to Bopomofo.

[0] https://groups.google.com/forum/#!topic/chewing-devel/Qj4bdZtN2ZA
