### ISSUE TITLE
使用許氏、倚天26鍵時，後來的聲母不會取代編輯區原有的聲母

### ISSUE THREAD

**Issue by hiunnhue** [chewing/libchewing#170]
預設鍵盤（預期的行為，與自然輸入法相同）：

1. 原本想輸入「ㄅ」卻誤按了「ㄆ」
2. 只要再按ㄅ，就會直接取代錯誤的ㄆ

許氏、倚天26鍵：

1. 先輸入ㄆ，再輸入ㄅ
2. 編輯區中的ㄆ保持不變

Env:

1. libchewing: 0.4.0+201501042131+1205~ubuntu14.04.1 (from PPA)
2. ibus-chewing: 1.4.10.1-1

**Comment by czchen** [comment]
For Hsu, the problem is in [here](https://github.com/chewing/libchewing/blob/1bb9288125bdc12009dd273ecc46b106f2798305/src/bopomofo.c#L389-L391). Instead of overwriting `ㄆ`, libchewing skips this search and tries to find if `b` can match other bopomofo. So at the end, `b` is discarded.

**Comment by czchen** [comment]
The problem is that hsu maps multiple bopomofo into single key. So libchewing does not know if user want to overwrite existing bopomofo or type a new bopomofo. Not sure if this is a bug or not.

**Comment by hiunnhue** [comment]
@czchen 
Could you take a look, please? I am not sure if this is the correct solution, but it passed the test case. If there's no other problem, then I'll apply this to layout ET26 later and make a pull request.

Thank you.  :-)

**Comment by czchen** [comment]
@hiunnhue 
I am not sure if overwriting existing bopomofo is good idea in Hsu, ET26 keyboard or not. I only use default keyboard. Maybe you can discuss it in <https://groups.google.com/forum/#!forum/chewing-devel>.

**Comment by hiunnhue** [comment]
see:
 https://groups.google.com/forum/#!topic/chewing-devel/kT60S_2XF1I

**Comment by czchen** [comment]
@hiunnhue Please send a PR for this issue using overwrite algorithm, thanks.
