### ISSUE TITLE
Migrate from Google Code to GitHub

### ISSUE THREAD

**Issue by Chocobo1** [chewing/libchewing#180]
Google Code is going to shutdown (although slowly):
[Official statement](http://google-opensource.blogspot.tw/2015/03/farewell-to-google-code.html)

Better make sure everything (e.g. wiki, reported issues) is migrated before the deadline.

**Comment by jserv** [comment]
The information about issue tracker is changed.

**Comment by kcwu** [comment]
For this ticket, Is there anything remain to do?

**Comment by czchen** [comment]
I think everything is in Github now. Please reopen this if anything is missing.
