### ISSUE TITLE
請問這有辦法上傳詞庫給大家用嗎？

### ISSUE THREAD

**Issue by laichiaheng** [chewing/libchewing#184]
譬如一些人名之類的

**Comment by laichiaheng** [comment]
現在詞庫實在是太舊了，很多早該存在的名詞都沒有

**Comment by czchen** [comment]
有哪些名詞需要新增？可以舉例嗎？

**Comment by laichiaheng** [comment]
快捷鍵、做法、浣腸劑
剩下的因為用了幾天都已經被紀錄起來了，所以要想一下
請問你們會加入網路用語嗎？

**Comment by laichiaheng** [comment]
大強子對撞機、弦理論、超弦理論、薛丁格、薛丁格的貓

**Comment by laichiaheng** [comment]
顴骨

**Comment by laichiaheng** [comment]
陳菊、賴清德、顏清標、連勝文、郝龍斌、林佳龍、胡志強、葛瑪蘭、新住民

**Comment by YamiOdymel** [comment]
沒被 Closed 的話，我仍然覺得有必要。

**Comment by PeterDaveHello** [comment]
Related comnent:
https://github.com/chewing/libchewing/pull/197#issuecomment-203315368

**Comment by edwardhome** [comment]
大推這個建議～
