### ISSUE TITLE
Chewing 好像沒有辦法輸出頓號 、

### ISSUE THREAD

**Issue by petani** [chewing/libchewing#19]
Chewing 用了好一陣子，一直有個不方便的地方，在輸入中文符號頓號時，找不到產生頓號的方法，情急之下只好改 

/usr/share/libchewing3/chewing/swkb.dat   

把字母 l 的對應改成 、

不知道有沒有更好的方法呢？

**Comment by dingze-0309** [comment]
```
```
```
