### ISSUE TITLE
候選清單未正確地開啟

### ISSUE THREAD

**Issue by hiunnhue** [chewing/libchewing#192]
步驟：
1. 取消後方選詞
2. 輸入：```實際，測試，設計，歷史```
3. 將游標移動至「計」的前面
4. 按↓開啟選字清單
5. 應該出現「計」的候選字，但卻出現「計，歷」的候選詞

環境：
fcitx-chewing: 0.2.1-1
libchewing: 0.4.0+201509041801+1282~ubuntu14.04.1

**Comment by kidwm** [comment]
Please report to fcitx-chewing.

https://github.com/taylorchu/fcitx-chewing

**Comment by hiunnhue** [comment]
Hi,
我現在用的是 ``ibus-chewing 1.4.10.1-1`` ，也有同樣的問題。
