### ISSUE TITLE
無法Ctrl+Num加詞(學習新詞)

### ISSUE THREAD

**Issue by astronid** [chewing/libchewing#193]
無法使用Ctrl+數字鍵學習新的詞，只要一按Ctrl字就送出了無法停留在選字欄，因此無法學習詞彙

環境
ibus-chewing 1.4.14-2
libchewing3 0.4.0-3
Xubuntu 15.10

**Comment by kidwm** [comment]
Please report to ibus-chewing.

https://github.com/definite/ibus-chewing
