### ISSUE TITLE
I cannot change my single word in some cases (Ubuntu 14.04)

### ISSUE THREAD

**Issue by robert501128** [chewing/libchewing#208]
When I was trying to change my word "心" to "新", I got some error
image
![image](https://cloud.githubusercontent.com/assets/12629785/14040145/13fb491a-f29f-11e5-8843-efbd476d770f.png)

as you can see, the word "心" is affected by the vocabulary "用心", so I can only change the vocabulary "用心", not the word "心"

**Comment by hiunnhue** [comment]
會不會是要再多按一次向下鍵，切換候選詞的長度？例如輸入「茶葉蛋」，然後將游標挪到「茶」的前面，就可以用向下鍵切換「茶葉蛋」→「茶葉」→「茶」。
