### ISSUE TITLE
Warning message for autogen.sh

### ISSUE THREAD

**Issue by jeffreyhc** [chewing/libchewing#218]
Environment: Ubuntu 15.04 64bit(in VM)

I execute autogen.sh before I run configure, and there comes to some warning message

```
src/tools/Makefile.am:21: warning: source file '$(top_srcdir)/src/common/chewing-utf8-util.c' is in a subdirectory,
src/tools/Makefile.am:21: but option 'subdir-objects' is disabled
automake: warning: possible forward-incompatibility.
automake: At least a source file is in a subdirectory, but the 'subdir-objects'
automake: automake option hasn't been enabled.  For now, the corresponding output
automake: object file(s) will be placed in the top-level directory.  However,
automake: this behaviour will change in future Automake versions: they will
automake: unconditionally cause object files to be placed in the same subdirectory
automake: of the corresponding sources.
automake: You are advised to start using 'subdir-objects' option throughout your
automake: project, to avoid future incompatibilities.
src/tools/Makefile.am:21: warning: source file '$(top_srcdir)/src/common/key2pho.c' is in a subdirectory,
src/tools/Makefile.am:21: but option 'subdir-objects' is disabled
src/tools/Makefile.am:21: warning: source file '$(top_srcdir)/src/porting_layer/src/plat_mmap_posix.c' is in a subdirectory,
src/tools/Makefile.am:21: but option 'subdir-objects' is disabled
src/tools/Makefile.am:21: warning: source file '$(top_srcdir)/src/porting_layer/src/plat_mmap_windows.c' is in a subdirectory,
src/tools/Makefile.am:21: but option 'subdir-objects' is disabled
src/tools/Makefile.am:21: warning: source file '$(top_srcdir)/src/porting_layer/src/rpl_malloc.c' is in a subdirectory,
src/tools/Makefile.am:21: but option 'subdir-objects' is disabled
src/tools/Makefile.am:15: warning: source file '$(top_srcdir)/src/common/chewing-utf8-util.c' is in a subdirectory,
src/tools/Makefile.am:15: but option 'subdir-objects' is disabled
src/tools/Makefile.am:15: warning: source file '$(top_srcdir)/src/common/key2pho.c' is in a subdirectory,
src/tools/Makefile.am:15: but option 'subdir-objects' is disabled
```

Are they normal? I don't have impression that I have seen those message before.

**Comment by redfish-lee** [comment]
Supposed that your automake version is [1.14.1](https://launchpad.net/ubuntu/vivid/+package/automake) which is default to 15.04

Refer to gnu automake [release note](https://lists.gnu.org/archive/html/automake/2013-06/msg00040.html):
>  - The next major Automake version (2.0) will unconditionally activate
    the 'subdir-objects' option.  In order to smooth out the transition,
    we now give a warning (in the category 'unsupported') whenever a
    source file is present in a subdirectory but the 'subdir-object' is
    not enabled.  For example, the following usage will trigger such a
    warning:
`bin_PROGRAMS = sub/foo
sub_foo_SOURCES = sub/main.c sub/bar.c`

I got the same warnings using 15.10 with automake 1.15.

**Comment by redfish-lee** [comment]
However this change will cause some `.po` files failed to be found bacause of non-recursive automake.
If we use non-resursive `subdir-objects` , some path of file link in Makefile.am should be modified.
**I'm not sure if it's necessary.**

In this way, remember to add a `--disable-dependency-tracking` options to find files well.
ex.
`./configure --prefix=/usr/ --disable-dependency-tracking`
