### ISSUE TITLE
linux mint 18 使用新酷音，右邊的數字鍵無法使用

### ISSUE THREAD

**Issue by liangliang01** [chewing/libchewing#228]
如標題
在使用ibus-chewing時，不管是中文模式還是英文模式

右邊的數字鍵按下去就是沒反應  沒辦法使用右邊的數字鍵直接輸入數字

**Comment by hiunnhue** [comment]
@liangliang01 

hi, 這個問題可能要回報到 ibus-chewing 那邊。

但是最新版 ibus-chewing (1.5.1) 應該已經解決這個問題，麻煩你先安裝 1.5.1 版試試看，如果還是有這個現象，再到 ibus-chewing 那邊回報。

回報時，別忘了附上 ...
1. ibus 版本
2. ibus-chewing 版本
3. libchewing 版本

**Comment by liangliang01** [comment]
好吧  感謝 
剛剛發現系統最新只能把新酷音更新到1.4
官方ppa又沒有給ubuntu 16.04版本更新的ppa  ＠＠
我在來研究一下好了 3Q~~

**Comment by kcwu** [comment]
resolved (not libchewing's own bug)

**Comment by escrowdis** [comment]
I met this issue on Ubuntu 16.04 LTS[1] and solve this by changing the option "Keyboard input method system" from **IBUS** to **fcitx** in _System Settings -> Language Support_

PS:
[1]
```
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.6 LTS
Release:	16.04
Codename:	xenial
```
