### ISSUE TITLE
在注音的倚天鍵盤下，打出ㄘ和ㄦ有困難

### ISSUE THREAD

**Issue by xcrewdriver** [chewing/libchewing#229]
版本：0.14

在注音的倚天鍵盤排列下，若輸入第一個按鍵是「'」（要打出ㄘ，例如：存在），則不會出現注音ㄘ，只會在螢幕上出現'
同樣，若輸入第一個按鍵是「=」（要打出ㄦ，例如：兒童），也不會出現注音ㄦ，只會在螢幕上出現=

提供給開發者參考。
謝謝。

**Comment by hiunnhue** [comment]
@xcrewdriver 

嗨，請問你用的輸入平台是 PIME 0.14 對嗎？

我這邊使用 ibus-chewing 1.5.1 沒有這個現象，所以應該是 PIME 那邊的問題。

**Comment by xcrewdriver** [comment]
是的，我是使用 PIME 0.14
謝謝您的回覆，我會想辦法把問題向 PIME 那邊陳述。
再次感謝。
