### ISSUE TITLE
倚天26鍵盤注音輸入

### ISSUE THREAD

**Issue by kcc1967** [chewing/libchewing#235]
我使用倚天26鍵盤, 但發現許多注音本身並無法輸入, 例如ㄆㄇ ... 等等.
打 p+SPACE 會變成ㄡ, 但我需要 ㄆ 要如何輸入 ???
ps. 本文的 ㄆㄇ是用 copy/paste, 用別的輸入法先打好再貼過來的 !!!

**Comment by hiunnhue** [comment]
@kcc1967 
嗨，抱歉我本身沒在用倚天26鍵，但據我了解，在倚天26鍵裡，ㄆ和ㄡ都是由 P 鍵輸入，所以當你只按 P 鍵和聲調符號的時候，代表你想輸入的是 ㄡ。同理，當你只按 M 鍵的時候，但表你想輸入的是 ㄢ。

這應該是正確的反應？

**Comment by kcc1967** [comment]
如果排除ㄆㄇ (事實上有 37-26=11 個共用英文按鍵的注音符號有這個問題) 認為他們不是中文的一部分, 那這就會是 "正確的反應".  我會遇到這個問題是因為我剛好再處理要給小學一二年級看的文件, 所以我常常需要輸入單獨的注音符號 ;-(

其實解法很簡單, 當我打 p+SPACE 時, 在ㄡ的選字單中併入ㄆ即可, 雖然 "怪怪的", 但只要是使用倚天26的人應該能接受這種怪怪的才對, 因為他們知道ㄡㄆ一同出現是什麼原因.

**Comment by kcc1967** [comment]
這真是太好了 !! 感謝 ;-)
