### ISSUE TITLE
WIN7 64位元無法開啟新酷音設定選單

### ISSUE THREAD

**Issue by lazypigy** [chewing/libchewing#236]
PIME v0.15.2
熱鍵和設定值的內容、設定新酷音輸入法，均無法開啟。
爬文修改configTool.py 及 config.js 兩個檔案也是無效。

**Comment by yan12125** [comment]
聽起來是PIME的問題，https://github.com/EasyIME/PIME 這裡應該較多能回答的人

**Comment by lazypigy** [comment]
好的，我去那問問看，因為我在PIME之前的版本就遇過同樣問題。

**Comment by kcwu** [comment]
reported to https://github.com/EasyIME/PIME/issues/214
close this one.
