### ISSUE TITLE
希望能加入"shift+space"的功能開關

### ISSUE THREAD

**Issue by angberserker** [chewing/libchewing#269]
很多人因為不習慣windows8以上開關輸入法的設定
目前最相似的設定是雙中文輸入法，其中一邊永久輸出英文，再用autokey將#space用^space取代
如此可以用^space切換，而且切換後不會把未確認(enter)的文字清除
可是近來發生一個問題
若以新酷音來進行純英文輸出時，常常因為用shift大寫單一詞彙後，按space造成轉換全形
既然都能將shift轉換語言關閉了，能否新增shift+space的開關，抑或者在英文/中文模式下shift+space的開關

使用版本：PIME chewing 1.1.0

**Comment by yan12125** [comment]
這個功能可能比較適合在 https://github.com/EasyIME/PIME/issues 討論。libchewing主要是負責核心的演算法，包含選字、詞彙學習演算法等等。

**Comment by angberserker** [comment]
好的，不好意思第一次來到這邊，比較不清楚分類，造成困擾抱歉了。
等我電腦開好我會再去改，謝謝

2017年6月9日 下午12:23，"Yen Chi Hsuan" <notifications@github.com>寫道：
