### ISSUE TITLE
fedora 29 ibus-chewing not work

### ISSUE THREAD

**Issue by skygrango** [chewing/libchewing#297]
kernel 4.18.7
ibus 1.5.19-3
ibus-chewing 1.6.1-4

在輸入法來源看不到chwing 
從ibus-setup的輸入法中有看到 但加入後沒有作用

wayland及xorg都沒有辦法使用

若有需要補充資訊的話，還請勞煩提醒

**Comment by yan12125** [comment]
You may want to report this to https://github.com/definite/ibus-chewing/issues instead.

**Comment by skygrango** [comment]
ok , thanks for response. :)
