### ISSUE TITLE
無法打「ㄐ」

### ISSUE THREAD

**Issue by jidanni** [chewing/libchewing#298]
我輸入 "j1"
找到 「ㄓ」，
無法打「ㄐ」。
亦即漢語拼音模式下無法打個 「ㄐ」字。

**Comment by yan12125** [comment]
Apparently the author of libchewing thinks there's no ㄓ in Pinyin

https://github.com/chewing/libchewing/blob/05bb0becd749510493273884a8262fe038fe5624/src/pinyin.c#L274

**Comment by jidanni** [comment]
我用 zh1, zhi1 均找的到 ㄓ。反而 ㄐ 難找。

**Comment by yan12125** [comment]
這段code是 https://github.com/chewing/libchewing/commit/ad9691c2a98d418f51228aeda0a3d9d349ae5bf7 加進去的。作者看起來應該是 @whsyu ？請問有什麼想法嗎？

**Comment by jidanni** [comment]
只知道我選漢語拼音模式，希望不受[其他方案干擾](jidanni.org/lang/pinyin/older.html)。
