### ISSUE TITLE
選詞字、音配對錯誤造成後續打出的詞語錯誤 failure to fit the pronounciations and the Chinese character when memorizing words

### ISSUE THREAD

**Issue by ShamrockLee** [chewing/libchewing#301]
自動記憶詞彙抓取的字錯誤，造成注音與文字對應錯誤，無法正確打出該詞語。附上編輯器的螢幕「有截」（另一次同類錯誤，正確詞語為「截圖」）和螢幕錄影（GIF 檔、 ZIP 檔）。
The auto- word-memorizing function sometimes grabs the wrong Chinese characters, leading to the false relations between the pronunciations and the characters. 
Here is a screenshot of the word in the window of chewing-editor, in which the the characters being chosen is incorrect.
![2019-02-09 15-13-41](https://user-images.githubusercontent.com/44064051/52518413-2dab8a00-2c85-11e9-8acc-22c284d7f48c.png)
It makes it unable to type the words before it is removed using the editor.
![chewing_failure_201902091515](https://user-images.githubusercontent.com/44064051/52518945-a105c980-2c8e-11e9-97a9-afc6423cb74c.gif)
Chewing versions:
```
shamrock@shamrock-mint64-201809:~/圖片/frames$ apt version libchewing3
0.5.1-1
shamrock@shamrock-mint64-201809:~/圖片/frames$ apt version libchewing3-data
0.5.1-1
shamrock@shamrock-mint64-201809:~/圖片/frames$ apt version chewing-editor
0.1.1-1
```
Here is the screen-recorded videos:
[chewing_bug.zip](https://github.com/chewing/libchewing/files/2847688/chewing_bug.zip)

**Comment by yan12125** [comment]
可能是有錯誤的資料進入了新酷音的資料庫。可以上傳你的家目錄下的 `.chewing/chewing.sqlite3` 嗎？

**Comment by yan12125** [comment]
> Here is a screenshot of the word in the window of chewing-editor, in which the the characters being chosen is incorrect.

Sorry I didn't notice this line. There's definitely an incorrect line in the database. Now the problem is why such an entry is added...

**Comment by ShamrockLee** [comment]
為了打出想打的字，目前字、音配對出錯的詞大部分已移除。（它們可能是在打字時被自動加入的）
以下為我的家目錄 ~/.chewing/chewing.sqlite3 壓縮檔：
當中有一處「結報」被寫成「人結」（但注音為「結報」），即為這種錯誤的結果。

已刪除部份內容。但由於打字詞彙可能涉及個人隱私，請勿用於任何資料提取與進行任何無關的利用。

[chewing_sqlite3_out.zip](https://github.com/chewing/libchewing/files/3195139/chewing_sqlite3_out.zip)

**Comment by hiunnhue** [comment]
Hi, 

請問是不是和這個狀況類似：https://github.com/chewing/libchewing/issues/232

**Comment by ShamrockLee** [comment]
看起來是。
這已經修復的嗎？這樣的話可以關掉 issue 了。感謝！
期待新版發布！
![Screenshot_2019-07-11_22-08-08](https://user-images.githubusercontent.com/44064051/61058413-c8bdb100-a429-11e9-9a09-2d7fd1735ead.png)
