### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by yan12125** [chewing/libchewing#307]
The last release [0.5.1](https://github.com/chewing/libchewing/releases) is more than 3 years ago, and there are quite a few fixes and improvements since then. For example, the fix for https://github.com/chewing/libchewing/issues/232 prevents more incorrect phrases from entering users' databases. How about releasing a new version?

I'm the current maintainer of the [libchewing](https://www.archlinux.org/packages/community/x86_64/libchewing/) package at Arch Linux. Usually we package stable versions only. It would be great to have better libchewing packaged in Arch Linux.

**Comment by ShamrockLee** [comment]
@jserv, @czchen 

What are the tests and procedures needed before a new release?
Bug-fix #232 is certainly worth a new release. Is there something we can help?

**Comment by yan12125** [comment]
> What are the tests and procedures needed before a new release?

An approach for testing is using libchewing-git every day. I've done that for months and everything looks good :100:

Also, a job to do before the next release might be bumping the .so version (libchewing.so.3 -> libchewing.so.4) as the size of a public `struct` is changed in https://github.com/chewing/libchewing/commit/5466d3302d8d2daf0da69a1b87f5230e663dd605#diff-7a29a56a9c3638f774d8e18248e7450b.

**Comment by jserv** [comment]
I agree with @yan12125. There should be a new release of libchewing this year. @czchen, how do you think?

**Comment by yan12125** [comment]
> Also, a job to do before the next release might be bumping the .so version (libchewing.so.3 -> libchewing.so.4)

I created #314 for this.

**Comment by ShamrockLee** [comment]
Will it take place next month?
Looking forward to it.

**Comment by yan12125** [comment]
@czchen @jserv 2020 is coming to an end. Is there still a plan to release a new version this year?

**Comment by ShamrockLee** [comment]
The Chinese new year is coming :firecracker:! A new release would be a great new-year's resolution :heavy_check_mark:.

**Comment by czchen** [comment]
The `ChewingContext` is only exported as pointer in public API, so I don't think bumping soversion is needed.

**Comment by yan12125** [comment]
I think people can create a `ChewingConfigData` object, fill fields manually and pass it to `chewing_Configure()`? Fields after `bAutoLearn` will have different offsets in older and newer libchewing. Codes using `sizeof(ChewingConfigData)` may be broken as well - a test was added to make sure `sizeof(ChewingConfigData)` does not change: https://github.com/chewing/libchewing/commit/8a2395c1b8f756275e0e915cbf79f7ccb4ebbdd3.

**Comment by czchen** [comment]
`chewing_Configure` and `ChewingConfigData` are both deprecated, so we shall keep them as is (e.g. https://github.com/chewing/libchewing/commit/77acaf9b52f0b85e428afb08b1acaf284eb92634).

**Comment by yan12125** [comment]
That makes sense. I will try the approach mentioned at https://github.com/chewing/libchewing/pull/314#issuecomment-1407796357.

**Comment by yan12125** [comment]
> we shall keep them as is

Fix proposed: https://github.com/chewing/libchewing/pull/372

**Comment by yan12125** [comment]
Here comes [v0.6.0-rc.1](https://github.com/chewing/libchewing/releases/tag/v0.6.0-rc.1). Looking forward to v0.6.0 stable!

**Comment by yan12125** [comment]
0.6.0 is released, thanks everyone involved!
