### ISSUE TITLE
It no longer works on Gnome 3.36

### ISSUE THREAD

**Issue by laichiaheng** [chewing/libchewing#312]
IBUS can't detect it.

**Comment by laichiaheng** [comment]
Never mind, it works again.

**Comment by laichiaheng** [comment]
結果發現 ibus-daemon 根本沒有正常運行，必須要在終端機打 `ibus-daemon&exit` 才有辦法在終端機關閉的狀況下正常使用中文輸入法，打完 `ibus-daemon&` 再打 `exit` 也不行。

**Comment by chengyus** [comment]
背景：
 選這篇是因為我覺得這個Issue 比較反應我遇到的狀況。 我確實有因為Ubuntu 建議我升級一些Gnome 的套件，但我原本就忘了裝 libchewing.  

相關指令敘述：
joseph@joseph$ history 10

  772  ibus-setup # 我大概是想去找那個像鍵盤的圖示的設定，沒找著因為我 fcitx相關套件全移掉了( ibus 很穩 沒有不穩)
  773  ibus-daemon -drx  # 打好玩的
  774  ibus-daemon -drx --panel /usr/lib/ibus/ibus-ui-gtk3  # 從 arch wiki 看到 一樣打好玩的
  775  hk4g4  # 看到酷音出現在 ibus & gnome & ubuntu 選單後 很興奮 在 x11 gtk2 shared library 還沒 load 好以前 隨便亂打幾個注音符號 出來英文 
  776  ibus-setup # 很懷念 ibus-setup 雖然 Ubuntu 19.10 的電源按鈕符號已經有個直連語言的齒輪符號。
  777  sudo apt-get install --reinstall libgtk2.0-0  # **關鍵點**. 谷歌搜尋了 "libgtk-x11-2.0.so.0 ubuntu 19.10" 因為在終端機看到它 missing. 
  778  ibus-setup  # 裝完上面 777 行的套件後， ibus-setup 的設定可以按了, 那個直連語言的齒輪符號的設定按鈕也可以按了。
  779  # 測試！ 可以。

(可能裝完 libgtk2.0-0 我有登出在登入）
希望有跟我遇到同樣狀況的人可以順利使用 好用的 libchewing. 今天在 Linux 模式下看開源碼和閱讀比較久才又開中文輸入法。

-Joseph
