### ISSUE TITLE
在某些地方無法使用右側數字鍵盤輸入所有數字

### ISSUE THREAD

**Issue by CollieIsCute** [chewing/libchewing#324]
- brave 版本
  - brave-browser-stable 1.25.68
- ibus 版本
  - 1.5.22-2ubuntu2.1 amd64
- ibus-chewing
  - focal,now 1.6.1-1 amd64
- 在特定環境中（brave browser中），無法以右側鍵盤輸入除了3,5,9以外的所有數字。
- 但是無法輸入不是完全無法輸入，在我亂打測試時，大概每打幾十個3,5,9以外的數字，也會打出一兩個原本的數字（會變成非3,5,9的數字，但是其他時候則會變成end, del, home...等等功能）。其他時候該按鍵會表現的跟把 numLock 鎖上時相同。
- 若使用鍵盤上方的數字鍵則正常

**Comment by yan12125** [comment]
我在以下的環境測試，右側數字鍵1~9都能正常輸入。可能是舊版本的問題。

* Arch Linux
* ibus-chewing 1.6.1.r14.g8e17848
* ibus 1.5.24
* brave 1.25.70

**Comment by redoc-dnarg** [comment]
喔對了！後來我同學也有同樣的情況，他說還要加上是使用gnome, 一換到XFCE問題就消失了

Chih-Hsuan Yen ***@***.***> 於 2021年6月11日 週五 14:56 寫道：

**Comment by yan12125** [comment]
FWIW, 我是在LXQt測試的。

我嘗試安裝GNOME測試ibus-chewing，卻無法切換到新酷音，暫時無法再深入探究。

GNOME是Wayland或X11？Wayland會不時有一些小問題。

**Comment by redoc-dnarg** [comment]
我是 X11, ibus 也是時好時壞，怪怪的。
後來放棄使用ibus, 換fcitx也有點用起來不順，最後再換gcin問題才解決

Chih-Hsuan Yen ***@***.***> 於 2021年6月12日 週六 10:13 寫道：

**Comment by yan12125** [comment]
gcin更新挺勤快的，可惜不再支援新酷音了，我也沒有能力重整gcin的新酷音模組。

https://hyperrate.com/thread.php?tid=34154

**Comment by redoc-dnarg** [comment]
qq
有些東西ibus的確蠻人性化的，但是那個數字鍵大bug用不下去，只好先用gcin,等待大神把ibus救起來🤣🤣

Chih-Hsuan Yen ***@***.***> 於 2021年6月12日 週六 23:51 寫道：

**Comment by edwardhome** [comment]
systemOS: Ubuntu 20.04 AMD64
ibus 版本: 1.5.22-2ubuntu2.1
ibus-chewing: 1.6.1-1

我也同樣遇到該問題，不過比較有趣的是一般情況下例如在Chrome 123456789 的數字鍵是可以輸入的
但是我在`Visual studio code`的文字編輯界面 僅能輸入 **3** **5** **9** ...

有趣的是，底下的終端機可以正常的輸入數字，點擊上方的文字編輯區變無法輸入其他按鍵
而且無論numlock 是否啟用，差異僅有無`end` `home`等相關功能

**Comment by yan12125** [comment]
和 https://github.com/definite/ibus-chewing/issues/157 這邊似乎是相同的問題

**Comment by yan12125** [comment]
聽起來是某些版本的瀏覽器有問題。請問以上提到的Visual studio code和Chrome分別是什麼版本呢？

**Comment by edwardhome** [comment]
Visual studio code 目前是 1.60.0 使用ibus+新酷音會有 數字鍵 **3** **5** **9** 無法使用的問題
然後我目前**改用fcitx**就沒有上述的問題了

另外，chrome 有問題之後我就沒有使用，剛剛回頭確認，發現目前在ibus下已經正常
chrome 版本為 93.0.4577.82 (正式版本) (64 位元)

**Comment by yan12125** [comment]
根據目前的資訊，以下軟體版本會有這個問題：

* Brave 1.25.68: 以 [Chromium 91.0.4472.77](https://github.com/brave/brave-core/commits/v1.25.68) 為基礎。
* Visual Studio Code 1.60.0: 使用 [Electron 13.1.8](https://github.com/microsoft/vscode/blob/1.60.0/package.json#L134) ，而後者以 [Chromium 91.0.4472.164](https://www.electronjs.org/releases/stable?version=13&page=2#13.1.8) 為基礎。

而 Chrome 93.0.4577.82 則沒有這個問題。一個可能是，這是舊版 Chrome/Chromium 的問題。

最新的 Electron 14.0.0 已經升級到 [Chromium 93.0.4577.58](https://www.electronjs.org/releases/stable#stack-upgrades-1400) ，等 Visual Studio Code 採用新版 Electron ，問題可能就解決了。

另外，最新的 Brave 1.29.81 也已經升級到 [Chromium 93.0.4577.82](https://github.com/brave/brave-core/commits/v1.29.81) ，可能已經沒有這個問題了。

**Comment by kidwm** [comment]
在有人再遇上這問題之前先關囉
