### ISSUE TITLE
LibChewing 是不是無法處理 Big5 字集外的漢字？

### ISSUE THREAD

**Issue by ShikiSuen** [chewing/libchewing#328]
我嘗試編譯一份簡體中文詞庫，編譯系統卻返回這個錯誤：

![image](https://user-images.githubusercontent.com/3164826/148191954-6b387fc8-c1dc-4ca0-8c54-5c50609985a7.png)

**Comment by ShikiSuen** [comment]
奇怪的是在 macOS 系統下 跑 cmake ./ 就一切正常。

**Comment by ShikiSuen** [comment]
靠，make install 時出錯了。不過總算看懂錯誤內容了。
![image](https://user-images.githubusercontent.com/3164826/148193201-b61b3a26-0731-49ca-ba6a-65dbcd26538e.png)

**Comment by yan12125** [comment]
似乎分析詞庫的程式覺得「合」沒有「ㄍㄜˇ」這個音，即使`phone.cin`已經包含了這個音：

https://github.com/chewing/libchewing/blob/452f6221fbad90c0706a3963b17e226216e40dd7/data/phone.cin#L8445

（PS: 此處為大千鍵盤對應的英文字）

請問能夠分享你使用的詞庫檔嗎？我試著在`tsi.src`加入這一行：
```
公合 1 ㄍㄨㄥ ㄍㄜˇ
```
libchewing仍然能夠編譯。

**Comment by ShikiSuen** [comment]
@yan12125 這邊可以拿去用：
https://github.com/ShikiSuen/libvchewing-data
但是這個辭庫目前尚未完善，至少要想成功藉由 libchewing 編譯的話需要確保 phone.cin 存在任何被詞組用到的字音。
我這一個月都在調整威注音的 macOS 版本。

P.S.: 威注音的 Windows 版本會是新酷音 TSF 的 fork。

**Comment by ShikiSuen** [comment]
@yan12125 微注音詞庫自己有自己的phone.cin（是用makefile自動生成的）。那個裡面沒有ge3音，所以才出錯。

**Comment by yan12125** [comment]
讓 `phone.cin` 裡面有 ㄍㄜˇ 應該就能編譯了？

**Comment by ShikiSuen** [comment]
@yan12125 程式的這個步驟是在檢查 tsi.src 是否有出現 phone.cin 沒有規定的讀音。

**Comment by yan12125** [comment]
就我的理解是的，所以如同前面你提到的，需要讓phone.cin包含任何詞組用到的讀音。

**Comment by ShikiSuen** [comment]
暫時關票，因為這個問題屬於 MSVC 編譯器自身對 CodePage 依賴使然。
程式本身還是能正常處理 Big5 以外的字的，只不過對 Surrogate-Pair 支援有問題（會另外開票）。
