### ISSUE TITLE
工作上遇到的一些常用錯字。「獨占」「身分」「香菸」等等

### ISSUE THREAD

**Issue by kuroutaakatsuki** [chewing/libchewing#331]
搜尋「法律統一用字表」可以找到其他用字。
挑幾個使用率特別高。
我都自己開sqlite修改user_freq跟max_freq解決。

不過選字時，錯的大多會顯示在最上面。
沒自己開sqlite大幅修正freq數值的話，很容易跑回來又要瘋狂打同樣的字，才能讓它記憶住。

話說orig_freq的用途到底是。
一直搞不清楚三個參數之間的差異。0x0

【常用字】（兩者都有，預設優先度是錯的比較高）
占據、獨占、占有、占有率、攻占、市占、市占率：　「佔」跟「占」。普遍用「占」。
發布、公布、分布、分布圖、宣布、布置：　「佈」跟「布」。普遍用「布」。
部分、身分：　「份」跟「分」，普遍用「分」。
身分證、畢業證書、證明書：　「証」跟「證」，普遍用「證」。　
香菸、菸酒、抽菸：　「煙」跟「菸」，普遍用「菸」。
電表、水表：　「錶」跟「表」，普遍用「表」。
給與：　「與」跟「予」，兩者都有用到，但普遍情況是「給與」的使用率比較高。
復查：　「複」跟「復」，普遍用「復」。
澈底：　「徹」跟「澈」，普遍用「澈」。
番茄、番薯： 「蕃」跟「番」，普遍用「番」。
雇主、聘雇、雇用： 「僱」跟「雇」，普遍用「雇」。
藍芽、藍牙：正式用語為「藍牙」。

【錯字】
摩托車：　原本詞庫應該只有錯字「摩拖車」。
供應鏈：　原本詞庫應該只有錯字「供應鍊」。
失聯：　原本詞庫應該只有錯字「失連」。
撫卹金： 　原本詞庫應該只有「撫恤金」。
亞洲盃： 　原本詞庫應該只有「亞洲杯」。

【拼音錯誤】
ㄓˊ ㄉㄜ˙：值得
ㄑㄧㄥ ㄌㄧㄥˊ：蜻蜓
ㄆㄢˋ ㄙˇ：拚死
ㄇㄛˋㄌㄨㄛˋ：脈絡

【沒必要】
添了、黏了：●了有很多被當作詞彙紀錄在基本詞庫。但是「超過二十天了」容易變成「超過二十添了」、「已經幾年了」變成「已經幾黏了」等等。總總打字經驗會發現「●了」的預設反而容易造成選字誤判。

【意義不明】
對心、能趕、抄有、十葉

**Comment by ShikiSuen** [comment]
請問您是用什麼密碼成功開啟 sqlite 檔案並編輯的呢？

**Comment by kuroutaakatsuki** [comment]
> 請問您是用什麼密碼成功開啟 sqlite 檔案並編輯的呢？

C:\Users\使用者\AppData\Roaming\PIME\chewing
到這裡找chewing.sqlite3開起來編輯。
不需要密碼喔。

**Comment by ShikiSuen** [comment]
@kuroutaakatsuki 謝謝。看來架構有改變。
我在用新酷音 tsf，裡面的 libchewing 生成的 db 是有被加密的。

**Comment by ShikiSuen** [comment]
這些會不會都是 libTabe 原本就有的問題？

我對「佔」與「佈」持另外意見，認為都需要用人字旁（因為都是動詞）。
「占」僅用作占卜的意思；「布」僅用作布匹的意思。這樣可以維持繁體中文本身的書面表達精確性。
「僱」與「雇」意義完全重合、且各自沒有別的意思，倒是可以統一至第二種寫法。

至於律政用詞在這方面有需求的話，新酷音可以引入使用者自訂詞語替代的功能。
這樣一來，在遞交 inline composition buffer 的時候，便可以自動批配這種取代規則。
（先取代長詞，後取代短詞、且不會影響到已經取代過的長詞。這個算法我還不太熟悉。）

「番茄」「番薯」是漢語寫法，對應的日語寫法是「蕃薯」「蕃藷」。
重編國語辭典倒是有提到「蕃薯」「蕃茄」，但點進去之後都是沒有詞條的。
<img width="349" alt="image" src="https://user-images.githubusercontent.com/3164826/175795418-5b48a75c-7a6d-4e9f-8b66-4c17d36565e5.png">
<img width="606" alt="image" src="https://user-images.githubusercontent.com/3164826/175795405-9d587615-9695-4cec-9244-695c3134fa8f.png">

「澈底」與「徹底」應該算是彼此使用率五五分成吧。

```
部分、身分：　「份」跟「分」，普遍用「分」。
身分證、畢業證書、證明書：　「証」跟「證」，普遍用「證」。　
香菸、菸酒、抽菸：　「煙」跟「菸」，普遍用「菸」。
電表、水表：　「錶」跟「表」，普遍用「表」。
給與：　「與」跟「予」，兩者都有用到，但普遍情況是「給與」的使用率比較高。
復查：　「複」跟「復」，普遍用「復」。
```
這幾個我倒是同意（唯獨「身份」代指在中國大陸頒發使用的身份證件，這是唯一例外情形）。
寫給過客們留意：是簡體中文的話，通常用「身份」，而不用「身分」。
