### ISSUE TITLE
請問新酷音是怎樣實現大千26鍵的支援的？

### ISSUE THREAD

**Issue by ShikiSuen** [chewing/libchewing#336]
我最近用 Swift 新寫了一個注音輸入法並擊輸入處理引擎。
https://github.com/ShikiSuen/Tekkon

目前對於複合注音排列支援目前只有倚天忘形26與許氏國音排列而已。
近期想考慮支援大千26鍵，但我只懂 Swift。
不知是否有熟悉新酷音的這個處理流程的人樂意講一下新酷音的大千26鍵的處理邏輯？

**Comment by ShikiSuen** [comment]
輪流切換	ㄆ	ㄅ
輪流切換	ㄊ	ㄉ
輪流切換	ㄔ	ㄓ	
輪流切換	ㄛ	ㄞ
輪流切換	ㄠ	ㄤ
輪流切換	ㄟ	ㄢ
輪流切換	ㄣ	ㄦ

文脈替換	ㄙ	ㄥ
	// 如果有聲母和介母在，則韻母為「ㄥ」。
	// 其餘情況，令聲母為「ㄙ」。
文脈替換	ㄖ	ㄝ
	// 如果有聲母和介母在，則韻母為「ㄝ」。
	// 其餘情況，令聲母為「ㄖ」。
條件切換	ㄩ	ㄡ
	// 如果說介母是「ㄩ」且韻母不是ㄡ的話，則介母清空、韻母變「ㄡ」。
	// 還如果介母非「ㄩ」且韻母就是ㄡ的話，則介母變「ㄩ」、韻母清空。
	// 還如果介母非空的話，令韻母為「ㄡ」。
條件切換	ㄧ	ㄚ	ㄧㄚ
	// 如果說介母是「ㄧ」且韻母不是「ㄚ」的話，則清空介母、且插入「ㄚ」。
	// 還如果介母非「ㄧ」且韻母就是「ㄚ」的話，則令介母為「ㄧ」。
	// 還如果介母是「ㄧ」且韻母就是「ㄚ」的話，則清空介母與韻母。
	// 還如果介母非空的話，令韻母為「ㄚ」。

目前仍未搞懂的是下述四個按鍵，用輪流切換是否真的沒問題：

輪流切換	ㄗ	˙
輪流切換	ㄍ	ˊ
輪流切換	ㄐ	ˇ
輪流切換	ㄎ	ˋ

**Comment by kidwm** [comment]
寫 Swift 的話也可以參考小麥注音？

https://github.com/openvanilla/McBopomofo

**Comment by ShikiSuen** [comment]
@kidwm 小麥 Swift 只是寫了一半。組字引擎、辭典引擎、KeyHandler、注音拼音並擊引擎都還是 C++ / Objective-C++。
我的全都是 Swift 寫的。

**Comment by ShikiSuen** [comment]
@kidwm 這是威注音輸入法，除了用到的 OpenCC 以及某個只有 ObjC 才有的原始基礎函數（isPrintable）以外都是純 Swift 的。
https://gitee.com/vchewing/vChewing-macOS

**Comment by ShikiSuen** [comment]
@kidwm 我還在用 C# 重寫整個輸入法的跨平台通用總成模組「LibvChewingNT」。
組字引擎與注拼並擊引擎都寫好了：
https://github.com/ShikiSuen/TekkonNT
https://github.com/ShikiSuen/MegrezNT

目前在寫辭典引擎：

<img width="1359" alt="image" src="https://user-images.githubusercontent.com/3164826/174489328-4a0530ee-94a3-4a13-b7d6-fc43e0da3274.png">

**Comment by mlouielu** [comment]
不確定還有沒有幫助，但是可以參考 #414

**Comment by ShikiSuen** [comment]
感謝 @mlouielu 的答覆。
這個問題已經 out of date 了，先關單處理。
