### ISSUE TITLE
著 與 着

### ISSUE THREAD

**Issue by showwish** [chewing/libchewing#341]
中國的網文圈裡 還是使用 着 居多
希望可以把這個對應改回來

**Comment by yan12125** [comment]
就我所知，新酷音一直是以台灣的使用習慣維護詞庫。在台灣「著」是列為正體字，「着」列為異體字 [1]。新酷音從最初的版本到現在也是「著」的頻率比較高，應該沒有「改回來」的問題。如果想要符合中國的使用習慣，可能需要另外維護詞庫。

[1] https://dict.variants.moe.edu.tw/variants/rbt/word_attribute.rbt?educode=A03506

**Comment by showwish** [comment]
不好意思，我好像沒有說明得很清楚
因為新酷音後來有簡體輸出，加上後來跑去寫網文，
覺得簡體輸出比用word的繁簡轉換更好用
這陣子就一直使用新酷音的簡體輸出

昨天介紹程式給朋友發現又有最新的版本有修正了
好幾個繁簡轉換都有修正過來，可是著這個字＠＠ 
出乎意料地又變回繁體字，雖然是異體字
不過確定簡體輸出的話，[著]這個字 還是 [着]這個字才對
請問想自己對應修正的話～也是用您說的那個網頁修正嗎？

**Comment by yan12125** [comment]
最新版本的 PIME 1.3.0-beta2 的確不會將「著」轉換為「着」，請問您是使用這個版本嗎？

我看了一下，PIME 內部是使用 OpenCC 做繁簡轉換，而 OpenCC 不會轉換「著」[1]。我對 OpenCC 不太瞭解，不確定要修改什麼檔案才會轉換「著」。

[1] https://github.com/BYVoid/OpenCC/issues/555

**Comment by showwish** [comment]
太奇怪了....真的是最新的版本....刚刚又去下载了一次...=.=无奈 还是一样著急 急著....XD
看樣子得刪整個檔案夾看看了QQ

**Comment by yan12125** [comment]
抱歉我可能沒說清楚，最新版 (PIME 1.3.0-beta2) 對「著」的處理是有問題的。如果需要正確轉換「著」，得先用舊的版本。

**Comment by showwish** [comment]
懂了！謝謝你的回答，因為舊版本的是其他的字一樣有問題....
所以～還是用新版好了，只是看改哪個字.....XD~~~~~
