### ISSUE TITLE
feat: add logging and tracing

### ISSUE THREAD

**Issue by kanru** [chewing/libchewing#358]
The original chewing logging module can be replaced by the `tracing` create.

We need to port important logging to Rust modules and add tracing instrument to all public interfaces.

However, we should avoid logging too detailed key and phrase info by default. Traces can be streamed to console or remote depending on the subscriber used, so we should avoid it become a key logger.

**Comment by ianchen-tw** [comment]
I would like to work on this one

**Comment by ianchen-tw** [comment]
I'll update my progress here:

1. The header file for public interface is`include/chewingio.h` -> implemented in `src/chewingio.c`
2. Existing C macros for logging resides in `src/private.h` (`LOG_VERBOSE`, `LOG_ERROR`, ...)

**Comment by yan12125** [comment]
> Write a python script that drive libchewing via `ctypes`.

Is this related? https://github.com/chewing/libchewing/blob/master/contrib/python/chewing.py
