### ISSUE TITLE
希望整合Fcitx 5的全形模組

### ISSUE THREAD

**Issue by Bob-YsPan** [chewing/libchewing#391]
希望Chewing能夠整合Fcitx 5的全形模組(fcitx5-module-fullwidth)或是對於Fcitx 5框架提供更完整的全形字輸入支援
使用Fcitx 5 Chewing時不易輸入大寫的全形英文字以及全形的空格有時候真的蠻困擾，且亦沒有附帶螢幕小鍵盤等替代的輸入方案可用
而Fcitx 5又是Ubuntu等主流發行版會預裝的輸入法框架，正是使用者會最常用的

目前有詢問Fcitx相關的問題，看起來Chewing是還沒整合這個模組
https://github.com/fcitx/fcitx5/issues/728

系統：Ubuntu Mate 22.10
框架版本：5.0.12-1

**Comment by kanru** [comment]
也許可以提供全形模式的行為讓輸入法框架可以自己設定

**Comment by wengxt** [comment]
從 fcitx 的角度來說，問題就是 libchewing 需要提供一個完全禁用本身全形功能的開關（包括禁用 shift + space 切換功能）
，然後只需要額外增加一行代碼就可以像其他的 fcitx 輸入法那樣非常簡單的直接調用 fcitx 的全形功能了。

從 api 的角度來說 shift + space 的實際功能對 fcitx 來說是黑盒，所以我不想直接在 fcitx的 engine 代碼裡面不將 shift +space 傳給 libchewing。

**Comment by kanru** [comment]
現在有 API 可以開關全形模式，但是沒有可以完全關掉全形模式
這可以考慮一下在新版支援。
