### ISSUE TITLE
提議開放這個 Repository 的 Discussion 版面。

### ISSUE THREAD

**Issue by ShikiSuen** [chewing/libchewing#393]
不然的話，有些與 bug 提報無關的詢問，開 issue 直接問的話，可能不太合適。

比如說我這次想問的是「請問 libchewing 目前對 Dvorak 許氏的相容處理是直接翻譯英文鍵盤、還是在此基礎上做了[像是這篇文章當中所講的那樣的](http://magicbetw.blogspot.com/2017/05/for-dvorak-layout.html)追加的佈局修改？」

**Comment by kanru** [comment]
我是覺得可以打開 Discussion 沒關係，但是也可以用 https://groups.google.com/group/chewing-devel/ 討論喔

目前 Dvorak 應該是先對應到 QWERTY 然後一般的許氏，也就是依照原本許氏鍵盤的注音符號位置

https://github.com/chewing/libchewing/blob/master/capi/chewing-internal/src/bopomofo.rs#L69-L73

**Comment by ShikiSuen** [comment]
@kanru 非常感謝。這是很重要的情報。
這直接證明了這十幾年來台澎金馬用 Dvorak Hsu 的人可能都在用這套方案。
（於是我這邊省了很多事情。真的太謝謝了。）
