### ISSUE TITLE
在高解析度螢幕下使用時選字清單會變得很小

### ISSUE THREAD

**Issue by JohnSuperAdler** [chewing/libchewing#400]
我最近開始在新筆電上工作，環境如下：

OS WIN11
解析度 2880x1800
顯示縮放比例 200％

![image-1](https://github.com/chewing/libchewing/assets/46437534/49098c89-5336-461f-9181-3ff3627fc631)

這個清單文字大小在14吋螢幕上顯示時顯然太小了，並且貌似沒有隨著200％的設定放大文字，可以請開發團隊嘗試改善這個問題嗎？謝謝。

**Comment by yan12125** [comment]
請問是使用 PIME 嗎？可以試試看 設定新酷音輸入法 -> 選字視窗外觀 -> 選字及訊息視窗文字大小

**Comment by JohnSuperAdler** [comment]
> 請問是使用 PIME 嗎？可以試試看 設定新酷音輸入法 -> 選字視窗外觀 -> 選字及訊息視窗文字大小

是的，已經找到按鈕並且解決問題了，感謝！
