### ISSUE TITLE
Potential to break libchewing compatibility when adding new keyboard layout

### ISSUE THREAD

**Issue by mlouielu** [chewing/libchewing#412]
Current keyboard layout enum in `bopomofo-private.h` is the following:

https://github.com/chewing/libchewing/blob/197b7015305a1147231bccdeeb974c38be13b055/include/internal/bopomofo-private.h#L30-L45

And some of the code in `bopomofo.c` use this to distinguish bopomofo and pinyin input method:

https://github.com/chewing/libchewing/blob/197b7015305a1147231bccdeeb974c38be13b055/src/bopomofo.c#L667

It has the potential to break compatibility when adding new keyboard layout (insert before `KB_HANYU_PINYIN`), which let adding new keyboard layout difficult. It also affect `KB_CARPALX` which is not a pinyin keyboard.

Adding a new function to distinguish this may be a way to solve this problem.

**Comment by kanru** [comment]
Good point. It seems current code assumes everything after `KB_HANYU_PINYIN` is a pinyin keyboard.

**Comment by kanru** [comment]
On second thought this is not breaking any ABI.

The enum values are part of the API/ABI so they should never change once added. To add new keyboard type, append them to the end of the enum list.

In bopomofo.c we know exactly what kbtype they are. The check at https://github.com/chewing/libchewing/blob/197b7015305a1147231bccdeeb974c38be13b055/src/bopomofo.c#L667 is a bug.

**Comment by mlouielu** [comment]
Closed by #441, further new keyboard layout needs to take care of `BopomofoKbIsPinyin()`.
