### ISSUE TITLE
Confusion around licenses for rust and non-rust codes

### ISSUE THREAD

**Issue by yan12125** [chewing/libchewing#433]
For rust codes, Cargo.toml says the license is `LGPL-2.1-or-later` [1]. On the other hand, README says `GNU LGPL v2.1` and does not include a phrase like "any later version" [2]. Could you clarify whether the license for non-rust codes is `LGPL-2.1-only` or `LGPL-2.1-or-later`?

This question is motivated by a proposal to move Arch Linux packages to SPDX license identifiers [3], where `LGPL-2.1-only` and `LGPL-2.1-or-later` are considered as different license identifiers [4]. As the maintainer of the libchewing package [5] in Arch Linux, I'd like to check which license identifier I should use in the package metadata.

[1] https://github.com/chewing/libchewing/blob/v0.6.0/Cargo.toml#L4
[2] https://github.com/chewing/libchewing/blob/v0.6.0/README.md?plain=1#L311
[3] https://rfc.archlinux.page/0016-spdx-license-identifiers/
[4] https://spdx.org/licenses/
[5] https://www.archlinux.org/packages/extra/x86_64/libchewing/

**Comment by kanru** [comment]
I believe our intention was to release with `LGPL-2.1-or-later`, although it was not explicitly stated in the README or COPYING file. This is also how Debian and Fedora currently interprets the license.

Let's see if @jserv and @czchen think otherwise.

**Comment by jserv** [comment]
> I believe our intention was to release with `LGPL-2.1-or-later`, although it was not explicitly stated in the README or COPYING file. This is also how Debian and Fedora currently interprets the license.

`LGPL-2.1-or-later` is exactly what this project is licensed under.

**Comment by kanru** [comment]
By the way, rust crates are often statically linked to the resulting binaries. Should we add an static link exception to allow other projects to choose their own license?

**Comment by kanru** [comment]
After some searching it seems that the combined work after static linking can still be released with other compatible licenses, as long as the end user is able to relink the program with a different version of the library.

For our purpose I don't think there's any difference with or without linking exceptions. I think we don't have to do anything.

**Comment by yan12125** [comment]
Thank you both for clarifications! I will use `LGPL-2.1-or-later` in the Arch Linux package later if Mr. ChangZhuo Chen does not raise a concern.

**Comment by czchen** [comment]
LGPL-2.1-or-later looks good to me.

**Comment by yan12125** [comment]
Thanks! I updated the Arch Linux package accordingly.  The next step might be updating README etc.

**Comment by yan12125** [comment]
I proposed an update in https://github.com/chewing/libchewing/pull/436

There are some other files using different licenses:
* [scripts/lcov.sh](https://github.com/chewing/libchewing/blob/master/scripts/lcov.sh): seems [MIT](https://opensource.org/license/mit/)
* [scripts/git2cl](https://github.com/chewing/libchewing/blob/master/scripts/git2cl): GPL-2.0-or-later

They are unused and going to be removed anyway (https://github.com/chewing/libchewing/issues/428), so I didn't mention licenses for them.
