### ISSUE TITLE
使用上下鍵選字（Use arrow keys to select characters）

### ISSUE THREAD

**Issue by leafpool243** [chewing/libchewing#455]
我習慣用上下鍵選字，因為其他中文輸入法都是用上下鍵選字的。

2020年有人在 fcitx5-chewing 開了 issue，＠wengxt 說：
> Chewing 的按键行为都是 libchewing 控制的，看起来并没有很多可以自定义某个按键行为的办法。**建议提交给 libchewing。**
https://github.com/fcitx/fcitx5-chewing/issues/2#issuecomment-687641077
<hr>
I'm used to using the up and down arrow keys to select characters because that's what all other Chinese IMEs do.

In 2020, someone opened an issue at fcitx5-chewing, but @wengxt said that the key behaviour was controlled by libchewing instead and suggested that an issue be opened here, but it doesn't appear like that was ever done.

**Comment by kanru** [comment]
為了確定我了解你的使用方法，可以請你舉個例子嗎？

比如說輸入「hk4g4<下鍵>」應該會出現選字單，你說得是這個使用情境嗎？還是說出現選字單後繼續用方向鍵選擇你要的字？

**Comment by leafpool243** [comment]
我說的是出現了選字單後，要能夠繼續用上下鍵選字

例如
g4下鍵：出現選字單
![圖片](https://github.com/chewing/libchewing/assets/63614345/f3bdf414-46a9-4706-b930-d59f60ccf144)
繼續按下鍵：市、是、事、世、士
像微軟的注音輸入法一樣

**Comment by kanru** [comment]
是像這樣嗎？這是 gnome + ibus-chewing

[Screencast from 2024-03-21 23-25-16.webm](https://github.com/chewing/libchewing/assets/17571/fa5631c8-5a13-435c-b676-0405f26eb215)

**Comment by wengxt** [comment]
我主要的意见是 chewing 的 API 设计和按键处理上。So 显然 ibus-chewing 在 chewing_handle 系列的 API 上再铺了一层自己的代码处理候选词列表。这种代码的写法就是只能假定 libchewing 不会改变 chewing_handle_{Left,Right,Up,Down} 的行为。

实质上是将 ibus-chewing 的实现和 libchewing 的按键逻辑进行了强绑定

举个例子，libchewing 如果某天决定自己增加 API 改变某个 handle_XXX 的行为，engine 里写的这些逻辑将直接受到影响

而且，因为候选词光标目前只是 ibus -chewing 放在自己 engine 里的概念，preedit 也没有同步进行更新

我的意见是这些逻辑都应当在 libchewing 中实现，而不是在 ibus-chewing 中实现

**Comment by kanru** [comment]
我想我同意你的意見

如果加了這個功能的話，感覺應該要是預設關閉的，不然原本沒有處理，或是無法顯示目前候選詞的 UI 就會有一個隱形的游標在那裡。

因為要加新的 API，我先把這個問題放到 1.0 之後

**Comment by leafpool243** [comment]
> 是像這樣嗎？這是 gnome + ibus-chewing
> Screencast.from.2024-03-21.23-25-16.webm

是的

**Comment by palapapa** [comment]
下鍵還是不能選字，只能打開選字表，但之後還是必須用數字鍵選字
