### ISSUE TITLE
Found typos in NEWS:

### ISSUE THREAD

**Issue by kanru** [chewing/libchewing#538]
* `Buf fixed` -> `Bug fixed`

_Originally posted by @yan12125 in https://github.com/chewing/libchewing/discussions/537#discussioncomment-9447586_

**Comment by Apsurt** [comment]
I edited NEWS till v0.3.5 (Jul 28, 2013). If it makes sense to edit older news, I'll edit them.

**Comment by yan12125** [comment]
Thanks! That's more than enough in my opinion. Only archeologists/historians read NEWS from 10 years ago I guess :)
