### ISSUE TITLE
Redundant GitHub Actions since #535

### ISSUE THREAD

**Issue by yan12125** [chewing/libchewing#540]
**Describe the bug**

In #535, macos-14 is added to test building on AArch64, while macos-14 seems the same as macos-latest as of writing. For example, both https://github.com/chewing/libchewing/actions/runs/9095776255/job/24999722012 and https://github.com/chewing/libchewing/actions/runs/9095776255/job/24999723237 have this log message:

> Image: macos-14-arm64

So the newly-added test may not confirm the bug fix.

On the other hand, it seems `c_char` is `i8` on macos/aarch64 and `u8` on linux/aarch64 (https://github.com/rust-lang/rust/blob/1.78.0/library/core/src/ffi/mod.rs#L83-L144). Maybe that's why existing macos-latest tests did not catch FTBFS.

**To Reproduce**
N/A

**Expected behavior**
New test cases can confirm bug fixes

**Screenshots**
N/a

**Platform (please complete the following information):**
 - OS: [e.g. Ubuntu, Debian, Fedora, Arch] N/A
 - Desktop: [e.g. Gnome, KDE] N/A
 - IME: [e.g. ibus-chewing, fcitx-chewing] N/A
 - Version [e.g. 0.7.0] git-master

**Additional context**
N/A

**Comment by kanru** [comment]
Hmm, interesting. The January github announcement did say they will switch macos-latest to aarch64 around May.

Before switching to add macos-14 I have added a smoke test to cross compile linux aarch64. Maybe I can add that back.

**Comment by yan12125** [comment]
> Before switching to add macos-14 I have added a smoke test to cross compile linux aarch64. Maybe I can add that back.

Thanks!

By the way, it seems linux/aarch64 runner images on GitHub Actions are coming: https://github.com/actions/runner-images/issues/2536

> The January github announcement did say they will switch macos-latest to aarch64 around May.

Maybe the change was just rolled out to libchewing recently :)

**Comment by kanru** [comment]
> By the way, it seems linux/aarch64 runner images on GitHub Actions are coming: https://github.com/actions/runner-images/issues/2536

Unfortunately this is the macos-14 update. There's no mention of a Linux runner yet.

**Comment by yan12125** [comment]
Ouch, I got confused, sorry
