### ISSUE TITLE
支援簡單模式

### ISSUE THREAD

**Issue by kanru** [chewing/libchewing#556]
**Is your feature request related to a problem? Please describe.**

有些 integration 支援簡單模式，也就是沒有自動選詞斷詞的模式，libchewing 應該要可以直接支援這個模式。

**Describe the solution you'd like**

開啟簡單模式的時候，每一個字都只選擇最常用字，沒有斷詞或是選詞功能。

**Comment by hiunnhue** [comment]
Is this related to #9 ?
