### ISSUE TITLE
支援沒有音調或是只輸入部份注音的模式

### ISSUE THREAD

**Issue by kanru** [chewing/libchewing#557]
**Is your feature request related to a problem? Please describe.**

類似手機輸入法常見的輸入模式

**Describe the solution you'd like**

開啟無音調模式或是部份注音模式，如果只輸入部份注音，應該還是要可以自動選擇最接近的詞。

**Comment by jidanni** [comment]
沒錯，若正在學習某語言，被逼全打有助於學習。
但遲早欲打快一點。
