### ISSUE TITLE
怎麼 z*i 難打？

### ISSUE THREAD

**Issue by jidanni** [chewing/libchewing#585]
為何於 Debian 最近無法打所有
- 茲
- - originally I could type `zi1` 
- - now I need to type `zzi1`
- 之
- - originally I could type `zhi1` 
- - now I need to type `zhzhi1`

但過一會兒所有牽涉 z*i 無法打。

Also just to type 難 in the title above I needed nnan2.

Version info coming soon.

**Comment by jidanni** [comment]
Sounds like https://github.com/chewing/libchewing/issues/546
這樣下去整個 project o不ba  a不bo 不 保 ！ ！ ！

**Comment by kanru** [comment]
What's the chewing keyboard layout used?

**Comment by jidanni** [comment]
怎無法 dump 給您看？
Isn't there some shell command I can issue to give you the complete status of my setup?
I think you need to give me instructions on how to show you my details.

**Comment by jidanni** [comment]
剛為了打個茲 I needed "zzzzzzii1".

**Comment by kanru** [comment]
Do you want to try the fixed version?

Pre-built binary:
- https://people.debian.org/~koster/libchewing3_0.8.4-3~1.gbp4e7caf_amd64.deb
- https://people.debian.org/~koster/libchewing3_0.8.4-3~1.gbp4e7caf_amd64.deb.asc

Steps:
```
curl -O https://people.debian.org/~koster/libchewing3_0.8.4-3~1.gbp4e7caf_amd64.deb
curl -O https://people.debian.org/~koster/libchewing3_0.8.4-3~1.gbp4e7caf_amd64.deb.asc
gpg --verify libchewing3_0.8.4-3\~1.gbp4e7caf_amd64.deb.asc
sudo dpkg -i libchewing3_0.8.4-3\~1.gbp4e7caf_amd64.deb
```

Logut and login again after install.

**Comment by jidanni** [comment]
OK, it works now. Thanks!
P.S.,
```
$ gpg --verify libchewing3_0.8.4-3\~1.gbp4e7caf_amd64.deb.asc
gpg: assuming signed data in 'libchewing3_0.8.4-3~1.gbp4e7caf_amd64.deb'
gpg: Signature made 2024年06月30日 (週日) 06時22分06秒 CST
gpg:                using RSA key D890D33D6147E2F51E3386870A39354AB6E57DE1
gpg: Can't check signature: No public key
```

**Comment by jidanni** [comment]
超慘，原問題改善後，副作用來了：
- 打 `第 123 號`
- 僅得 `第 號`

**Comment by kanru** [comment]
> 超慘，原問題改善後，副作用來了： 打 `第 123 號`， 僅得 `第 號`, 否則必先切換英文，才能打半型數字。

Thanks for the report. I need the exact input sequence to reproduce. Do you type space?

**Comment by kanru** [comment]
Tracking the new issue in #592
