### ISSUE TITLE
如谷歌，打 one letter abbreviations

### ISSUE THREAD

**Issue by jidanni** [chewing/libchewing#588]
我於 Android and Chromebook, 用谷歌 Hanyu Pinyin (Traditional Chinese)
能打類似短短的
> smzytyzg

得
> 三民主義統一中國

希望 libchewing 某日亦然。

By the way, I gave up making a Chinese title for this issue, because the first letter of my pinyin's kept flying to the front of the line.

**Comment by yan12125** [comment]
Similar to https://github.com/chewing/libchewing/issues/557 ?
