### ISSUE TITLE
拼音模式應直接輸出非拼音符號

### ISSUE THREAD

**Issue by kanru** [chewing/libchewing#592]
打 `第 123 號`，
僅得 `第 號`, 否則必先切換英文，才能打半型數字。

_Originally posted by @jidanni in https://github.com/chewing/libchewing/issues/585#issuecomment-2211552491_

Test case:

```
ChewingContext *ctx;
ctx = chewing_new();
start_testcase(ctx, fd);
chewing_set_KBType(ctx, KB_HANYU_PINYIN);

type_keystroke_by_string(ctx, "pin yin  123 mo2shi4");
ok_preedit_buffer(ctx, "拼音 123 模式");

chewing_clean_preedit_buf(ctx);
chewing_delete(ctx);
```

**Comment by kanru** [comment]
@jidanni can you try this fixed version?

Pre-built binary:

* <https://people.debian.org/~koster/libchewing3_0.8.4-3~3.gbp6aaa9d_amd64.deb>

```
curl -O https://people.debian.org/~koster/libchewing3_0.8.4-3~3.gbp6aaa9d_amd64.deb
sudo dpkg -i libchewing3_0.8.4-3~3.gbp6aaa9d_amd64.deb
```

**Comment by jidanni** [comment]
OK, now it works.
