### ISSUE TITLE
Enhance Phrasing performance

### ISSUE THREAD

**Issue by czchen** [chewing/libchewing#73]
In function `FindInterval`. The following loop structure is used to find all intervals.

``` c
for ( begin = 0; begin < pgdata->nPhoneSeq; begin++ ) {
    for ( end = begin; end < pgdata->nPhoneSeq; end++ ) {
```

However, for system phrase, we do not need two nest loops to find the intervals. For example, if both phrases `一二` and `一二三四` are system phrases. When libchewing do tree traversal to find `一二三四`, phrase `一二` is in the middle of search path. So the second loop can be skip.

Userphrase, however, is another story.

**Comment by kanru** [comment]
See also https://github.com/chewing/libchewing/commit/06e0073fee373f0d79ab1489f56aab62ee8632ed

The performance is enhanced by using the assumption that better phrasing results are part of the top K shortest paths so we can reduce the search space to only consider K results.

I plan to add some benchmark to futher analysis current implementation.
